/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.applet.Applet;
import java.applet.AudioClip;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author alumno
 */
public class Intro extends javax.swing.JFrame {

    BarraDeProgreso b;
    
    public Intro() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MagmaSkin");
        b = new BarraDeProgreso(progreso, this);
        b.execute();
        
    }

    public class BarraDeProgreso extends SwingWorker<Integer, Void> {
    
    private JProgressBar progreso;
    private JFrame jf;
    
    public BarraDeProgreso(JProgressBar progreso, JFrame jf) {
        this.progreso = progreso;
        this.jf = jf;
    }
 
    @Override
    protected Integer doInBackground() throws Exception {
        jf.setVisible(true);
        jf.setLocationRelativeTo(null);
        progreso.setVisible(true);
        AudioClip sonido;
        sonido = Applet.newAudioClip(getClass().getResource("../sonido/intro.wav"));
        sonido.play();
        
        try{
        for(int i=0; i<=100; i++){
            progreso.setValue(i);
             Thread.sleep(150);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
       jf.dispose();
       Aplicacion nv = new Aplicacion();
       nv.setVisible(true);  
       return 0;
    }
    
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progreso = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 314, 550, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/intro.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar progreso;
    // End of variables declaration//GEN-END:variables
}
